eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-decoration:
      path: /api-decoration/**
      serviceId: decoration
    api-designer:
      path: /api-designer/**
      serviceId: designer
    api-product:
      path: /api-product/**
      serviceId: product